title: FAMAZOA - F-droid AndroidtimeMachine AndroZoo Open-source Applications
author: Bruno Góis Mateus
email: brunomateus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The largest publicy available dataset of Open-source applications written in Kotlin

twitter_username: 
github_username:  brunomateus

sass:
    style: compressed

collections:
    versions:
        output: true
        permalink: /:collection/:name
    current:
        output: true
        permalink: /stats



# Information related to FAMAZOA

number_of_apps: 388 
current_version: v3.0 
